version: 2.0

jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.54.0
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: echo $PWD; ls -lah
      - run: git status
      - run:
          name: "Build"
          command: make public
      - run:
          name: "Test"
          command: htmlproofer public --allow-hash-href --check-html --empty-alt-ignore --disable-external


