version: 2.1

jobs:
  build_and_publish:
    docker:
      - image: cibuilds/hugo:0.54.0
    working_directory: ~/project
    shell: /usr/bin/env bash -euo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "00:b6:0c:6b:77:f4:08:7e:06:0f:81:b2:43:09:2b:11"
      - run:
          name: Configure Git & SSH
          environment:
            GITHUB_PUBLIC_SSH_KEY: AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          command: |
            git version
            git config --global user.email "samsalisbury+fieldnotes-tech-bot@gmail.com"
            git config --global user.name "fieldnotes-tech-bot" 
            [ -d ~/.ssh ] || mkdir -p ~/.ssh
            echo "github.com ssh-rsa $GITHUB_PUBLIC_SSH_KEY" >> ~/.ssh/known_hosts
            # The following section only exists for local testing, to work around
            # a bug in the 'circleci local execute' command where it does not pass through
            # the private key despite setting the appropriate flag.
            [ "${SSH_PRIVATE_KEY:-x}" = x ] || {
              echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            }
      - run:
          name: Clone
          command: git clone git@github.com:fieldnotes-tech/fieldnotes.tech ~/project
      - run:
          name: Build
          command: make build
      - run:
          name: Publish
          command: make publish

workflows:
  publish:
    jobs:
      - build_and_publish
